//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Item", Namespace = "http://schemas.datacontract.org/2004/07/Database", IsReference = true)]
    public partial class Item : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CountryField;

        private System.DateTime Date_createdField;

        private string DescriptionField;

        private string EventField;

        private int Id_itemField;

        private string LandscapeField;

        private string PathField;

        private Database.Person[] PeopleField;

        private string TypeField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date_created
        {
            get
            {
                return this.Date_createdField;
            }
            set
            {
                this.Date_createdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Event
        {
            get
            {
                return this.EventField;
            }
            set
            {
                this.EventField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_item
        {
            get
            {
                return this.Id_itemField;
            }
            set
            {
                this.Id_itemField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Landscape
        {
            get
            {
                return this.LandscapeField;
            }
            set
            {
                this.LandscapeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path
        {
            get
            {
                return this.PathField;
            }
            set
            {
                this.PathField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Database.Person[] People
        {
            get
            {
                return this.PeopleField;
            }
            set
            {
                this.PeopleField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Person", Namespace = "http://schemas.datacontract.org/2004/07/Database", IsReference = true)]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string GenderField;

        private int Id_itemField;

        private int Id_personField;

        private Database.Item ItemField;

        private string NameField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_item
        {
            get
            {
                return this.Id_itemField;
            }
            set
            {
                this.Id_itemField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_person
        {
            get
            {
                return this.Id_personField;
            }
            set
            {
                this.Id_personField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Database.Item Item
        {
            get
            {
                return this.ItemField;
            }
            set
            {
                this.ItemField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "FilterModel", Namespace = "http://schemas.datacontract.org/2004/07/Database")]
    public partial class FilterModel : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CountryField;

        private string EventField;

        private string LandscapeField;

        private string[] PersonsField;

        private string TypeField;

        private System.Nullable<int> YearField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Event
        {
            get
            {
                return this.EventField;
            }
            set
            {
                this.EventField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Landscape
        {
            get
            {
                return this.LandscapeField;
            }
            set
            {
                this.LandscapeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Persons
        {
            get
            {
                return this.PersonsField;
            }
            set
            {
                this.PersonsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Year
        {
            get
            {
                return this.YearField;
            }
            set
            {
                this.YearField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IItemPerson")]
public interface IItemPerson
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/InterfaceItem/AddItem", ReplyAction = "http://tempuri.org/InterfaceItem/AddItemResponse")]
    int AddItem(Database.Item item);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/InterfaceItem/AddItem", ReplyAction = "http://tempuri.org/InterfaceItem/AddItemResponse")]
    System.Threading.Tasks.Task<int> AddItemAsync(Database.Item item);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/InterfaceItem/GetById", ReplyAction = "http://tempuri.org/InterfaceItem/GetByIdResponse")]
    Database.Item GetById(int id);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/InterfaceItem/GetById", ReplyAction = "http://tempuri.org/InterfaceItem/GetByIdResponse")]
    System.Threading.Tasks.Task<Database.Item> GetByIdAsync(int id);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/InterfaceItem/RemoveItem", ReplyAction = "http://tempuri.org/InterfaceItem/RemoveItemResponse")]
    void RemoveItem(int id);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/InterfaceItem/RemoveItem", ReplyAction = "http://tempuri.org/InterfaceItem/RemoveItemResponse")]
    System.Threading.Tasks.Task RemoveItemAsync(int id);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/InterfaceItem/GetAllItems", ReplyAction = "http://tempuri.org/InterfaceItem/GetAllItemsResponse")]
    Database.Item[] GetAllItems();

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/InterfaceItem/GetAllItems", ReplyAction = "http://tempuri.org/InterfaceItem/GetAllItemsResponse")]
    System.Threading.Tasks.Task<Database.Item[]> GetAllItemsAsync();

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/InterfaceItem/UpdateItem", ReplyAction = "http://tempuri.org/InterfaceItem/UpdateItemResponse")]
    string UpdateItem(int id, Database.Item newItem);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/InterfaceItem/UpdateItem", ReplyAction = "http://tempuri.org/InterfaceItem/UpdateItemResponse")]
    System.Threading.Tasks.Task<string> UpdateItemAsync(int id, Database.Item newItem);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/InterfaceItem/FilterItems", ReplyAction = "http://tempuri.org/InterfaceItem/FilterItemsResponse")]
    Database.Item[] FilterItems(Database.FilterModel filter);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/InterfaceItem/FilterItems", ReplyAction = "http://tempuri.org/InterfaceItem/FilterItemsResponse")]
    System.Threading.Tasks.Task<Database.Item[]> FilterItemsAsync(Database.FilterModel filter);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/InterfacePerson/AddPerson", ReplyAction = "http://tempuri.org/InterfacePerson/AddPersonResponse")]
    int AddPerson(Database.Person person);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/InterfacePerson/AddPerson", ReplyAction = "http://tempuri.org/InterfacePerson/AddPersonResponse")]
    System.Threading.Tasks.Task<int> AddPersonAsync(Database.Person person);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/InterfacePerson/GetPersonsForItem", ReplyAction = "http://tempuri.org/InterfacePerson/GetPersonsForItemResponse")]
    Database.Person[] GetPersonsForItem(int id);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/InterfacePerson/GetPersonsForItem", ReplyAction = "http://tempuri.org/InterfacePerson/GetPersonsForItemResponse")]
    System.Threading.Tasks.Task<Database.Person[]> GetPersonsForItemAsync(int id);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/InterfacePerson/GetNamePersons", ReplyAction = "http://tempuri.org/InterfacePerson/GetNamePersonsResponse")]
    string[] GetNamePersons();

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/InterfacePerson/GetNamePersons", ReplyAction = "http://tempuri.org/InterfacePerson/GetNamePersonsResponse")]
    System.Threading.Tasks.Task<string[]> GetNamePersonsAsync();

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/InterfacePerson/VerifyIfPersonExist", ReplyAction = "http://tempuri.org/InterfacePerson/VerifyIfPersonExistResponse")]
    int VerifyIfPersonExist(int id, string name);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/InterfacePerson/VerifyIfPersonExist", ReplyAction = "http://tempuri.org/InterfacePerson/VerifyIfPersonExistResponse")]
    System.Threading.Tasks.Task<int> VerifyIfPersonExistAsync(int id, string name);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/InterfacePerson/RemovePersons", ReplyAction = "http://tempuri.org/InterfacePerson/RemovePersonsResponse")]
    void RemovePersons(int id);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/InterfacePerson/RemovePersons", ReplyAction = "http://tempuri.org/InterfacePerson/RemovePersonsResponse")]
    System.Threading.Tasks.Task RemovePersonsAsync(int id);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/InterfacePerson/RemovePerson", ReplyAction = "http://tempuri.org/InterfacePerson/RemovePersonResponse")]
    void RemovePerson(Database.Person person);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/InterfacePerson/RemovePerson", ReplyAction = "http://tempuri.org/InterfacePerson/RemovePersonResponse")]
    System.Threading.Tasks.Task RemovePersonAsync(Database.Person person);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IItemPersonChannel : IItemPerson, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ItemPersonClient : System.ServiceModel.ClientBase<IItemPerson>, IItemPerson
{

    public ItemPersonClient()
    {
    }

    public ItemPersonClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public ItemPersonClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public ItemPersonClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public ItemPersonClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    public int AddItem(Database.Item item)
    {
        return base.Channel.AddItem(item);
    }

    public System.Threading.Tasks.Task<int> AddItemAsync(Database.Item item)
    {
        return base.Channel.AddItemAsync(item);
    }

    public Database.Item GetById(int id)
    {
        return base.Channel.GetById(id);
    }

    public System.Threading.Tasks.Task<Database.Item> GetByIdAsync(int id)
    {
        return base.Channel.GetByIdAsync(id);
    }

    public void RemoveItem(int id)
    {
        base.Channel.RemoveItem(id);
    }

    public System.Threading.Tasks.Task RemoveItemAsync(int id)
    {
        return base.Channel.RemoveItemAsync(id);
    }

    public Database.Item[] GetAllItems()
    {
        return base.Channel.GetAllItems();
    }

    public System.Threading.Tasks.Task<Database.Item[]> GetAllItemsAsync()
    {
        return base.Channel.GetAllItemsAsync();
    }

    public string UpdateItem(int id, Database.Item newItem)
    {
        return base.Channel.UpdateItem(id, newItem);
    }

    public System.Threading.Tasks.Task<string> UpdateItemAsync(int id, Database.Item newItem)
    {
        return base.Channel.UpdateItemAsync(id, newItem);
    }

    public Database.Item[] FilterItems(Database.FilterModel filter)
    {
        return base.Channel.FilterItems(filter);
    }

    public System.Threading.Tasks.Task<Database.Item[]> FilterItemsAsync(Database.FilterModel filter)
    {
        return base.Channel.FilterItemsAsync(filter);
    }

    public int AddPerson(Database.Person person)
    {
        return base.Channel.AddPerson(person);
    }

    public System.Threading.Tasks.Task<int> AddPersonAsync(Database.Person person)
    {
        return base.Channel.AddPersonAsync(person);
    }

    public Database.Person[] GetPersonsForItem(int id)
    {
        return base.Channel.GetPersonsForItem(id);
    }

    public System.Threading.Tasks.Task<Database.Person[]> GetPersonsForItemAsync(int id)
    {
        return base.Channel.GetPersonsForItemAsync(id);
    }

    public string[] GetNamePersons()
    {
        return base.Channel.GetNamePersons();
    }

    public System.Threading.Tasks.Task<string[]> GetNamePersonsAsync()
    {
        return base.Channel.GetNamePersonsAsync();
    }

    public int VerifyIfPersonExist(int id, string name)
    {
        return base.Channel.VerifyIfPersonExist(id, name);
    }

    public System.Threading.Tasks.Task<int> VerifyIfPersonExistAsync(int id, string name)
    {
        return base.Channel.VerifyIfPersonExistAsync(id, name);
    }

    public void RemovePersons(int id)
    {
        base.Channel.RemovePersons(id);
    }

    public System.Threading.Tasks.Task RemovePersonsAsync(int id)
    {
        return base.Channel.RemovePersonsAsync(id);
    }

    public void RemovePerson(Database.Person person)
    {
        base.Channel.RemovePerson(person);
    }

    public System.Threading.Tasks.Task RemovePersonAsync(Database.Person person)
    {
        return base.Channel.RemovePersonAsync(person);
    }
}
