//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace Database
{
    [DataContract(IsReference = true)]
    public partial class Person
    {
        [DataMember]
        public int Id_person { get; set; }
        [DataMember]
        public string Name { get; set; }
        [DataMember]
        public string Gender { get; set; }
        [DataMember]
        public int Id_item { get; set; }
        [DataMember]
        public virtual Item Item { get; set; }
    }
}
